/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package RitaFigurer;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author alebe18
 */
public class RitaFigurerJPanel extends javax.swing.JPanel {
    ArrayList<Figur> figurlista = new ArrayList<>();
    private String figur = "";
    /**
     * Creates new form RitaFigurerJPanel
     */
    public RitaFigurerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCirkel = new javax.swing.JButton();
        jbtnRektangel = new javax.swing.JButton();
        jbtnTriangel = new javax.swing.JButton();
        jbtnRensa = new javax.swing.JButton();

        jbtnCirkel.setText("Cirkel");
        jbtnCirkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCirkelActionPerformed(evt);
            }
        });

        jbtnRektangel.setText("Rektangel");
        jbtnRektangel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRektangelActionPerformed(evt);
            }
        });

        jbtnTriangel.setText("Triangel");
        jbtnTriangel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTriangelActionPerformed(evt);
            }
        });

        jbtnRensa.setText("Rensa");
        jbtnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnCirkel)
                .addGap(18, 18, 18)
                .addComponent(jbtnRektangel)
                .addGap(18, 18, 18)
                .addComponent(jbtnTriangel)
                .addGap(18, 18, 18)
                .addComponent(jbtnRensa)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCirkel)
                    .addComponent(jbtnRektangel)
                    .addComponent(jbtnTriangel)
                    .addComponent(jbtnRensa))
                .addContainerGap(271, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCirkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCirkelActionPerformed
        figur = "cirkel";
        
        int panelWidth = getWidth();
        int panelHeight = getHeight();
        
        int w = (int) (Math.random() * 150 + 15);
        int h = (int) (Math.random() * 150 + 15);
        
        int x = (int) (Math.random() * (panelWidth - w));
        int y = (int) (Math.random() * (panelHeight - h));    
            
        /*int R = (int) (Math.random() * 256);
        int G = (int) (Math.random() * 256);
        int B = (int) (Math.random() * 256);
        System.out.println("w: "+w);*/
        Figur c = new Cirkel (x, y, w);
            figurlista.add(c);
            repaint(); 
            
        
        
        
    }//GEN-LAST:event_jbtnCirkelActionPerformed

    private void jbtnRektangelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRektangelActionPerformed
        figur = "rektangel";
        
        int panelWidth = getWidth();
        int panelHeight = getHeight();
        
        int w = (int) (Math.random() * 150 + 15);
        int h = (int) (Math.random() * 150 + 15);
        
        int x = (int) (Math.random() * (panelWidth - w));
        int y = (int) (Math.random() * (panelHeight - h));    
            
        Figur r = new Rektangel (x, y, w, h);
            figurlista.add(r);
            repaint(); 
    }//GEN-LAST:event_jbtnRektangelActionPerformed

    private void jbtnTriangelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTriangelActionPerformed
        figur = "triangel";
        int panelWidth = getWidth();
        int panelHeight = getHeight();
        
        int w = (int) (Math.random() * 150 + 15);
        int h = (int) (Math.random() * 150 + 15);
        
        int x = (int) (Math.random() * (panelWidth - w));
        int y = (int) (Math.random() * (panelHeight - h)); 
    
        Figur t = new Triangel (x, y, w, h);
            figurlista.add(t);
            repaint();
    }//GEN-LAST:event_jbtnTriangelActionPerformed

    private void jbtnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRensaActionPerformed
        figur = "rensa";
        repaint();
    }//GEN-LAST:event_jbtnRensaActionPerformed

    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        for(int i = 0; i < figurlista.size(); i++){
            
            figurlista.get(i).rita(g);
        }
        
        if(figur.equals("rensa")){
            super.paintComponent(g);
        }/*
        int panelWidth = getWidth();
        int panelHeight = getHeight();
        
        int w = (int) (Math.random() * 150 + 15);
        int h = (int) (Math.random() * 150 + 15);
        
    
    if(figur.equals("cirkel")){
            
        int x = (int) (Math.random() * (panelWidth - w));
        int y = (int) (Math.random() * (panelHeight - h));    
            
        int R = (int) (Math.random() * 256);
        int G = (int) (Math.random() * 256);
        int B = (int) (Math.random() * 256);
        
        Color color = new Color(R, G, B);
        g.setColor(color);
        g.fillOval(x, y, w, w);
    }
        
    
    if(figur.equals("rektangel")){
    
        int x = (int) (Math.random() * (panelWidth - w));
        int y = (int) (Math.random() * (panelHeight - h));    
            
        int R = (int) (Math.random() * 256);
        int G = (int) (Math.random() * 256);
        int B = (int) (Math.random() * 256);
        
        Color color = new Color(R, G, B);
        g.setColor(color);
        g.fillRect(x, y, w, h);
}
    
    if(figur.equals("triangel")){
        int x = (int) (Math.random() * (panelWidth - w));
        int y = (int) (Math.random() * (panelHeight - h));
        int modX = (w + 10) / 2;
        int[] xPoints = {};
        int [] yPoints = {};
        
        int R = (int) (Math.random() * 256);
        int G = (int) (Math.random() * 256);
        int B = (int) (Math.random() * 256);
       
        Color color = new Color(R, G, B);
        g.setColor(color);
        g.fillPolygon(xPoints, yPoints, 3);
    }*/
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCirkel;
    private javax.swing.JButton jbtnRektangel;
    private javax.swing.JButton jbtnRensa;
    private javax.swing.JButton jbtnTriangel;
    // End of variables declaration//GEN-END:variables
}
